name: ci-neon

on:
  workflow_dispatch:
  schedule:
    # codziennie o 02:30 UTC (04:30 czasu PL w lecie)
    - cron: "30 2 * * *"

jobs:
  migrate-test-snapshot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install psql 17 (PGDG)
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg lsb-release
          echo "deb [arch=amd64] http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" | \
            sudo tee /etc/apt/sources.list.d/pgdg.list
          wget -qO- https://www.postgresql.org/media/keys/ACCC4CF8.asc | \
            gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/postgresql.gpg > /dev/null
          sudo apt-get update
          sudo apt-get install -y postgresql-client-17

          # sanity-check
          pg_dump --version
          psql --version

      - name: Make migration script executable
        run: chmod +x ./scripts/psql-migrate.sh

      - name: Run migrations on Neon
        run: ./scripts/psql-migrate.sh "$NEON_CS_URL"
        env:
          NEON_CS_URL: ${{ secrets.NEON_CS_URL }}

      - name: Build solution
        run: dotnet build catering-backend.sln -c Release --no-restore

      - name: Run Unit tests
        run: dotnet test ./tests/Unit -c Release

      - name: Run Integration tests (Neon)
        env:
          ConnectionStrings__Default: ${{ secrets.NEON_CS }}
        run: dotnet test ./tests/Integration -c Release

      - name: Run E2E tests (Neon)
        env:
          ConnectionStrings__Default: ${{ secrets.NEON_CS }}
        run: dotnet test ./tests/E2E -c Release

      - name: Snapshot (pg_dump custom format)
        run: |
          TIMESTAMP=$(date -u +"%Y%m%dT%H%M%SZ")
          F="neon_snapshot_${TIMESTAMP}.dump"
          pg_dump --no-owner -Fc "$NEON_CS_URL" -f "$F"
          echo "SNAPSHOT_FILE=$F" >> $GITHUB_ENV
        env:
          NEON_CS_URL: ${{ secrets.NEON_CS_URL }}

      - name: Upload snapshot artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SNAPSHOT_FILE }}
          path: ${{ env.SNAPSHOT_FILE }}
          retention-days: 7
